### PR TITLE
Initial fix for verifying rerouted entries

### PR DESCRIPTION
**Pull request by shankari**
Findings:
- all the legs had polylines defined
- for the vast majority of these, the polylines were defined in the waypoint_coords
    But they were defined within the geometry, not outside (should they be in the geometry? outside?)

The new Verify_rerouted_entries notebook allows us to verify the structure of the legs programatically
https://github.com/MobilityNet/mobilitynet-analysis-scripts/pull/48#issuecomment-777160586

The auto-fill code was not handling this correctly, which is why we ran into
https://github.com/MobilityNet/mobilitynet-analysis-scripts/pull/48#issuecomment-775538734
and
https://github.com/MobilityNet/mobilitynet-analysis-scripts/pull/48#issuecomment-776439847

We need to decide how we are representing polylines and handle them properly before proceeding with validation.

### CODE REVIEW

**Comment by shankari** [comment]
Where the polylines are defined

```
Checking leg walk_to_caltrain in trip mtv_to_berkeley_sf_bart
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg commuter_rail_aboveground in trip mtv_to_berkeley_sf_bart
Trajectory is defined using polyline, includes polyline True

Checking leg subway_underground in trip mtv_to_berkeley_sf_bart
Trajectory is defined using polyline, includes polyline True

Checking leg walk_to_bus in trip mtv_to_berkeley_sf_bart
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg city_bus_short in trip mtv_to_berkeley_sf_bart
Trajectory is defined using polyline, includes polyline True

Checking unimodal trip walk_urban_university
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg walk to the bikeshare location in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg ebike_bikeshare_urban_long in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg express_bus in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using polylines, includes polyline True

Checking leg walk_downtown_urban_canyon in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using waypoint_coords, includes polyline True

Checking leg light_rail_below_above_ground in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using polyline, includes polyline True

Checking leg commuter_rail_with_tunnels in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using polyline, includes polyline True

Checking leg inner_suburb_downtown_walk in trip berkeley_to_mtv_SF_express_bus
Trajectory is defined using waypoint_coords, includes polyline True
```

**Comment by shankari** [comment]
@singhish can you come up with a recommendation for:

> We need to decide how we are representing polylines and handle them properly before proceeding with validation.

by today's meeting. If the answer is to represent them always as `polylines`, then you also need to decide what to do about the original `waypoint_coords`. If there is a clear winner, you can implement it, otherwise, let's discuss in a few hours.

**Comment by singhish** [comment]
@shankari As of right now, my gut feeling as far as a design decision goes is that we should represent polylines at the root level of the leg, especially if `waypoint_coords` is redundant. However, to ensure I am understanding the question, what exactly was the purpose of `waypoint_coords` in the first case?

**Comment by shankari** [comment]
> As of right now, my gut feeling as far as a design decision goes is that we should represent polylines at the root level of the leg,

That makes sense.

> However, to ensure I am understanding the question, what exactly was the purpose of waypoint_coords in the first case?

To generate the routes for the first time. The polylines that we have now weren't generated from scratch. Instead, the trajectories were first created using the `waypoint_coords` or `relation` options. Now that we are combining the specs, we encoded the trajectories from `train_bus_ebike_mtv_ucb.filled.json` and `train_bus_ebike_sm_reroute_mtv_ucb.filled.json` into a polyline. This allowed us to ensure that the polylines matched the trajectories from months ago.

So the sequence was:
waypoints + OSM -> coordinates in separate files -> polylines in single file -> coordinates in single file

**Pull request merged**
